### ISSUE TITLE
How should I sign up for the Nansen Query Plan? to access BSC private datasets

### ISSUE THREAD

**Issue by dacelee** [nansen-ai/evmchain-etl-table-definitions#19]
How should I sign up for the Nansen Query Plan? to access BSC private datasets

**Comment by jasonbxu** [comment]
Hi! Right now we're in the alpha testing phase for Nansen Developer Plan. It might be easier to discuss in person. Would you be able to find a time to speak via this calend.ly link? https://calendly.com/jasonxu/30min
